---

# https://gohugo.io/documentation/
# https://gohugo.io/getting-started/configuration/
# https://docs.stack.jimmycai.com/

# https://roneo.org/en/a-newsletter-with-hugo-buttondown-and-netlify/

baseurl: https://www.procamora.com
languageCode: es
defaultContentLanguage: es
theme: hugo-theme-stack
#theme: hugo-theme-learn
paginate: 10
title: "#> fireroot"
enableRobotsTXT: true

outputs:
  home:
    - HTML
    - RSS
#    - JSON


languages:
  es:
    languageName: Español
    contentDir: content
    weight: 1
    sidebar:
      #      emoji: 🍥
      subtitle: Mi wiki donde escribo artículos sobre Linux, Ciberseguridad y temas relacionados.
      avatar:
        enabled: true
        local: true
        src: icons/procamora_30.png

  en:
    languageName: English
    contentDir: content
    weight: 2
    sidebar:
      #      emoji: 🍥
      subtitle: My wiki where I write articles about Linux, Cybersecurity and related topics.
      avatar:
        enabled: true
        local: true
        src: icons/procamora_30.png

# Change it to your Disqus shortname before using
disqusShortname : 'procamora-github'

# GA Tracking ID
googleAnalytics:

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
  post: /p/:slug/
  page: /:slug/



params:
  GithubEdit: "https://github.com/procamora/dummy/edit/main/content/"  # custom add
  DownnloadPDF: "/pdf/"  # option 1
  # DownnloadPDF: "https://github.com/procamora/dummy/raw/main/static/pdf/"  # option 2

  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  favicon: img/favicon.ico

  footer:
    since: 2020
    customText: Esto es el footer

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST



  article:
    math: true
    toc: true
    readingTime: true
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  comments:
    enabled: true
    provider: disqus  # set disqusShortname

#    provider: utterances  # https://utteranc.es/ and https://github.com/apps/utterances
#    utterances:
#      repo: procamora/dummy
#      issueTerm: pathname
#      label: utterances

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # Your Twitter username
      #            site: lomirus

      # Available values: summary, summary_large_image
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: false
      local: false
      src:

  colorScheme:
    # Display toggle
    toggle: true

    # Available values: auto, light, dark
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: -100
      params:
        icon: home

    - identifier: feed
      name: Feed
      url: /index.xml
      weight: -10
      params:
        icon: rss
  social:
    - identifier: github
      name: GitHub
      url: https://github.com/procamora
      params:
        icon: brand-github

    - identifier: linkedin
      name: Linkedin
      url: https://es.linkedin.com/in/pablo-rocamora
      params:
        icon: brand-linkedin

    - identifier: mail
      name: Gmail
      url: mailto:pablojoserocamora@gmail.com
      params:
        icon: brand-gmail  # https://fontawesomeicons.com/svg/icons/brand-gmail

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      ## Set to true if you have HTML content inside Markdown
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
